<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>Assembly-CSharp</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
	<!-- Core プロジェクトを参照 -->
	<ProjectReference Include="..\CurryEngine.Core\CurryEngine.Core.csproj" />
	<ProjectReference Include="..\CurryEngine.API\CurryEngine.API.csproj" />
  </ItemGroup>
  
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(OutDir)Assembly-CSharp.dll" DestinationFolder="$(MSBuildProjectDirectory)\..\x64\Debug\" />
	<Copy SourceFiles="$(OutDir)Assembly-CSharp.pdb" DestinationFolder="$(MSBuildProjectDirectory)\..\x64\Debug\" />
  </Target>
</Project>
