<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
	<AssemblyName>CurryEngine.Runtime</AssemblyName>
	<RootNamespace>CurryEngine.Runtime</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<EnableDynamicLoading>true</EnableDynamicLoading>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<BaseOutputPath>$(SolutionDir)</BaseOutputPath>
	<Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ComponentCache.cs" />
    <Compile Include="ComponentAccessor.cs" />
    <Compile Include="EngineRuntime.cs" />
    <Compile Include="GameObjectAccessor.cs" />
    <Compile Include="GameObjectCache.cs" />
    <Compile Include="HotReload\HotReloadManager.cs" />
    <Compile Include="HotReload\ScriptLoadContext.cs" />
    <Compile Include="BehaviourMethodCache.cs" />
    <Compile Include="NativeInputProvider.cs" />
    <Compile Include="Native\CollisionConverter.cs" />
    <Compile Include="Native\CollisionInfoDto.cs" />
    <Compile Include="Native\NativeMethods.cs" />
    <Compile Include="Native\ScriptBridge.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Reflection\FieldMeta.cs" />
    <Compile Include="Reflection\ScriptInspector.cs" />
    <Compile Include="ScriptRegistry.cs" />
    <Compile Include="TransformAccessor.cs" />
  </ItemGroup>
  <ItemGroup>
	  <!-- Core プロジェクトを参照 -->
	  <ProjectReference Include="..\CurryEngine.Core\CurryEngine.Core.csproj" />
	  <!--CurryEngine.Coreに対して内部可視性を許可する-->
	  <InternalsVisibleTo Include="CurryEngine.Core" />
	  <!--CurryEngine.APIに対して内部可視性を許可する-->
	  <InternalsVisibleTo Include="CurryEngine.API" />
	  
	  <Compile Include="$(SolutionDir)Generated\CSharp\Native\*.g.cs">
		  <Link>Native\%(RecursiveDir)%(Filename)%(Extension)</Link>
	  </Compile>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy /y &quot;$(SolutionDir)x64\$(Configuration)\net9.0\CurryEngine.Runtime.dll&quot; &quot;$(SolutionDir)x64\$(Configuration)\&quot;&#xD;&#xA;xcopy /y &quot;$(SolutionDir)x64\$(Configuration)\net9.0\CurryEngine.Runtime.runtimeconfig.json&quot; &quot;$(SolutionDir)x64\$(Configuration)\&quot;&#xD;&#xA;xcopy /y &quot;$(SolutionDir)x64\$(Configuration)\net9.0\CurryEngine.Runtime.deps.json&quot; &quot;$(SolutionDir)x64\$(Configuration)\&quot;&#xD;&#xA;xcopy /y &quot;$(SolutionDir)x64\$(Configuration)\net9.0\CurryEngine.Runtime.pdb&quot; &quot;$(SolutionDir)x64\$(Configuration)\&quot;" />
  </Target>

</Project>
